spring.application.name=carrental-app

spring.datasource.url=jdbc:postgresql://localhost:5432/carrental
spring.datasource.username=carrental
spring.datasource.password=carrental

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
